#!/bin/bash
cachedir=${XDG_CACHE_HOME:-"$HOME/.cache"}
histsize=50
if [ -d "$cachedir" ]; then
    hist=$cachedir/i3_hist
else
    hist=$HOME/.i3_hist # if no xdg dir, fall back to dotfile in ~
fi

cmd=$( tac "$hist" | dmenu "$@" )

if [[ -z $cmd ]]; then
    exit
fi

i3-msg "$cmd" &

sed -i "/^${cmd}$/d;${histsize}q" "$hist"
echo "$cmd" >> "$hist"

